FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Create necessary directories

# Set environment variables
ENV DATA_DIR="C:/Users/tejas/My Projects/Stock News Sentiment Analysis Webapp/data"
ENV CHARTS_DIR="C:/Users/tejas/My Projects/Stock News Sentiment Analysis Webapp/static/charts"
ENV PORT=8080
ENV PYTHONUNBUFFERED=1
ENV HUGGING_FACE_TOKEN="your hugging face key"

# Expose the port
EXPOSE 8080

# Run the application
CMD ["python", "app.py"]
